frontend:
  image: 15080316041/frontend
  tag: latest
  autoscaling:
    averageUtilization: 50

backend:
  image: 15080316041/backend
  tag: latest
  autoscaling:
    averageUtilization: 50

database:
  enabled: false
  uri: 192.168.0.51
  username: external_postgres
  password: external_postgres