frontend:
  image: 15080316041/frontend
  tag: 06d2754
  autoscaling:
    averageUtilization: 90
backend:
  image: 15080316041/backend
  tag: 06d2754
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
